<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
	<Actions category="Scripts">
		<text>Export Layer Anim</text>

		<Action name="export_layer_anim">
			<icon></icon>
			<text>Export Layer Anim</text>
			<whatsThis>Exports all root layers in distinct files</whatsThis>
			<toolTip>Exports all root layers in distinct files</toolTip>
			<iconText>ELA</iconText>
			<activationFlags>0</activationFlags>
			<activationConditions>0</activationConditions>
			<shortcut>ctrl+alt+shift+e</shortcut>
			<isCheckable>false</isCheckable>
			<statusTip></statusTip>
		</Action>
	</Actions>
</ActionCollection>